# Generated by Django 3.1.7 on 2021-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'Multi Choice Questions',
                'verbose_name_plural': 'Multi Choice Questions',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=150)),
                ('highest_education', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Multi Choice User',
                'verbose_name_plural': 'Multi choice',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('investor', models.BooleanField(blank=True, default=False)),
                ('account_linked', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
