# Generated by Django 3.1.7 on 2021-03-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_multichoiceanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoiceuser',
            name='uuid',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
