# Generated by Django 3.1.7 on 2021-03-21 11:44

from django.db import migrations, models
import questions.random_id


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210321_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoiceuser',
            name='uuid',
            field=models.CharField(blank=True, default=questions.random_id.random_id, max_length=150, null=True),
        ),
    ]
