# Generated by Django 3.1.7 on 2021-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_multichoiceanswer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
